#!/usr/bin/env bash
GKE_CLUSTER_NAME="${GKE_CLUSTER_NAME:-CHANGEME-scale-test}"
GKE_ROUTER_NAME="${GKE_ROUTER_NAME:-$GKE_CLUSTER_NAME-router}"
GKE_NETWORK_NAME="${GKE_SUBNET_NAME:-$GKE_CLUSTER_NAME-network}"
GKE_SUBNET_NAME="${GKE_SUBNET_NAME:-$GKE_CLUSTER_NAME-subnet}"
GKE_SUBNET_RANGE="${GKE_SUBNET:-192.168.1.0/24}"
GKE_DEV_REASON="${GKE_DEV_REASON:-100-node-scale-test}"
GKE_OWNER="${GKE_OWNER:-CHANGEME}"
GKE_N_NODES="${GKE_N_NODES:-100}"

CILIUM_VERSION="${CILIUM_VERSION:-1.14.0-snapshot.2}"
CILIUM_VALUES_FILE="${CILIUM_VALUES_FILE:-./cilium-values.yaml}"

CL2_PROVIDER="${CL2_PROVIDER:-gke}"
