name: Image build

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  check-changes:
    name: Create build matrix
    runs-on: ubuntu-latest
    outputs:
      excludes: ${{ steps.exclude.outputs.excludes }}
  
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        if: ${{ github.event_name == 'pull_request' }}
        with:
          persist-credentials: false
      
      - name: Check code changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        if: ${{ github.event_name == 'pull_request' }}
        id: changes
        with:
          filters: |
            cmapisrv-mock:
              - 'cmapisrv-mock/**'
            scale-utils:
              - 'egw-scale-utils/**'
      
      - name: Prep matrix exclude list
        id: exclude
        run: |
          if [[ "${{ github.event_name }}" == 'push' ]]; then
            echo "excludes=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo '["cmapisrv-mock", "scale-utils"]' | jq -c '[ .[] | select(any(. == '${{ steps.changes.outputs.changes }}'[]; .)) | { "name": . } ]' > /tmp/excludes.json

          echo "Generated excludes"
          cat /tmp/excludes.json

          echo "excludes=$(jq -c '.' /tmp/excludes.json)" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: check-changes

    strategy:
      matrix:
        include:
          - name: cmapisrv-mock
            context: cmapisrv-mock
            dockerfile: ./cmapisrv-mock/Dockerfile
          - name: scale-utils
            context: egw-scale-utils
            dockerfile: ./egw-scale-utils/Dockerfile
        exclude: ${{ fromJSON(needs.check-changes.outputs.excludes) }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Login to quay.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        if: ${{ github.event_name == 'push' }}
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME_SCAFFOLDING }}
          password: ${{ secrets.QUAY_PASSWORD_SCAFFOLDING }}

      - name: Checkout Source Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false

      - name: Build and Push
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6.4.1
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name == 'push' }}
          platforms: linux/amd64,linux/arm64
          tags: |
            quay.io/${{ github.repository_owner }}/${{ matrix.name }}:${{ github.event.pull_request.head.sha || github.sha }}
